nati_x86_64_defconfig: enable CONFIG_NFT_FIB_* and CONFIG_NLMON
It was observed that firewalld was failing on startup with the error

ERROR: COMMAND_FAILED: 'python-nftables' failed: internal:0:0-0: Error: Could
not process rule: No such file or directory

I used nlmon to debug this by capturing and partially decoding the netlink
traffic in wireshark. On that basis, I think setting CONFIG_NLMON=m was prudent.

That analysis implicating something fib-related in the nft kernel config. Those
modules weren't enabled; enabling them eliminates the error.

I'm also setting CONFIG_NFT_DUP_*=m to proactively avoid any potential
mysterious firewalld failures due to missing modules in the future.

Signed-off-by: Rich Tollerton <rich.tollerton@ni.com>
(cherry picked from commit 853ad5b299f897819c0d258ba4cc5dbddf9e01cb)
Signed-off-by: Gratian Crisan <gratian.crisan@ni.com>