nirtfeatures: Automatically select support for NEW_LEDS
Prior to commit 7142f92412c1 ("wireless: carl9170: fix LEDS build errors &
warnings") support for MAC80211_LEDS, NEW_LEDS and LEDS_CLASS config
options was automatically enabled by having CONFIG_CARL9170=m in
nati_x86_64_defconfig.

The aforementioned commit removed the automatic selection in favor of
CARL9170_LEDS config option declaring a dependency on MAC80211_LEDS.

This results in linker errors if the nirtfeatures driver is enabled via
CONFIG_NI_RT_FEATURES since this driver makes use of functionality provided
by the NEW_LEDS and LEDS_CLASS configuration options:

  LD      .tmp_vmlinux.kallsyms1
ld: drivers/misc/nirtfeatures.o: in function `nirtfeatures_parse_led_pie.isra.0':
nirtfeatures.c:(.text+0x103b): undefined reference to `devm_led_classdev_register_ext'
ld: drivers/misc/nirtfeatures.o: in function `nirtfeatures_acpi_add':
nirtfeatures.c:(.text+0x14ad): undefined reference to `devm_led_classdev_register_ext'
make: *** [Makefile:1179: vmlinux] Error 1

Automatically select support for NEW_LEDS and by extension LEDS_CLASS if
NI_RT_FEATURES is enabled.

Signed-off-by: Gratian Crisan <gratian.crisan@ni.com>